### ISSUE TITLE
Proposal Roadmap for improving and maintaining 

### ISSUE THREAD

**Issue by nutboltu** [patw0929/react-intl-tel-input#255]
@patw0929 , @superhit0 

Here's the proposed tasks that we can include in our roadmap.

- [x] Write a script for `libphonenumber.js` which will update monthly via `travis` job schedule
- [x] Add [storybook](https://github.com/storybooks/storybook) and moved examples to stories.
- [ ] Implement [semantic-release](https://github.com/semantic-release/semantic-release) for automatic release
- [x] Practise [conventionalcommits](https://www.conventionalcommits.org)
- [x] Add PR/ISSUE template

**Comment by superhit0** [comment]
`Write a script for libphonenumber.js which will update on google release` --> `let me think on the framework`

**Comment by nutboltu** [comment]
> * Implement [semantic-release](https://github.com/semantic-release/semantic-release) for automatic release
will be covered in #258
